// <auto-generated />
using System;
using DataAccessLayer.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20250108101332_migration2")]
    partial class migration2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EntityLayer.Concrete.Islemler", b =>
                {
                    b.Property<int>("IslemlerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IslemlerID"));

                    b.Property<int>("Adet")
                        .HasColumnType("int");

                    b.Property<int?>("MusteriID")
                        .HasColumnType("int");

                    b.Property<bool>("Satis")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("Tarih")
                        .HasColumnType("date");

                    b.Property<int>("ToplamFiyat")
                        .HasColumnType("int");

                    b.Property<int?>("ToptanciID")
                        .HasColumnType("int");

                    b.Property<int>("UrunID")
                        .HasColumnType("int");

                    b.HasKey("IslemlerID");

                    b.HasIndex("MusteriID");

                    b.HasIndex("ToptanciID");

                    b.HasIndex("UrunID");

                    b.ToTable("Islemler");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Musteriler", b =>
                {
                    b.Property<int>("MusteriID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MusteriID"));

                    b.Property<string>("MusteriAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MusteriSoyadi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MusteriID");

                    b.ToTable("Musteriler");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Toptancilar", b =>
                {
                    b.Property<int>("ToptanciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ToptanciID"));

                    b.Property<int>("Adet")
                        .HasColumnType("int");

                    b.Property<int>("SatisFiyati")
                        .HasColumnType("int");

                    b.Property<string>("ToptanciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UrunID")
                        .HasColumnType("int");

                    b.HasKey("ToptanciID");

                    b.HasIndex("UrunID");

                    b.ToTable("Toptancilar");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Urunler", b =>
                {
                    b.Property<int>("UrunID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UrunID"));

                    b.Property<string>("UrunAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UrunFiyat")
                        .HasColumnType("int");

                    b.Property<int>("UrunStok")
                        .HasColumnType("int");

                    b.HasKey("UrunID");

                    b.ToTable("Urunler");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Islemler", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Musteriler", "Musteri")
                        .WithMany("Islemler")
                        .HasForeignKey("MusteriID");

                    b.HasOne("EntityLayer.Concrete.Toptancilar", "Toptanci")
                        .WithMany("Islemler")
                        .HasForeignKey("ToptanciID");

                    b.HasOne("EntityLayer.Concrete.Urunler", "Urun")
                        .WithMany("Islemler")
                        .HasForeignKey("UrunID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musteri");

                    b.Navigation("Toptanci");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Toptancilar", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Urunler", "Urun")
                        .WithMany("Toptancilar")
                        .HasForeignKey("UrunID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Musteriler", b =>
                {
                    b.Navigation("Islemler");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Toptancilar", b =>
                {
                    b.Navigation("Islemler");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Urunler", b =>
                {
                    b.Navigation("Islemler");

                    b.Navigation("Toptancilar");
                });
#pragma warning restore 612, 618
        }
    }
}
